name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: ""
    required: true
    default: "World"
    
runs:
  using: "Docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
